package com.psbc.pojo;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class File04 implements TableModel {
	private String AppSheetSerialNo;
	private String TransactionCfmDate;
	private String CurrencyType;
	private String ConfirmedVol;
	private String ConfirmedAmount;
	private String FundCode;
	private String LargeRedemptionFlag;
	private String TransactionDate;
	private String TransactionTime;
	private String ReturnCode;
	private String TransactionAccountID;
	private String DistributorCode;
	private String ApplicationVol;
	private String ApplicationAmount;
	private String BusinessCode;
	private String TAAccountID;
	private String TASerialNO;
	private String BusinessFinishFlag;
	private String DiscountRateOfCommission;
	private String DepositAcct;
	private String RegionCode;
	private String DownLoaddate;
	private String Charge;
	private String AgencyFee;
	private String NAV;
	private String BranchCode;
	private String OriginalAppSheetNo;
	private String OriginalSubsDate;
	private String OtherFee1;
	private String IndividualOrInstitution;
	private String RedemptionDateInAdvance;
	private String StampDuty;
	private String ValidPeriod;
	private String RateFee;
	private String TotalBackendLoad;
	private String OriginalSerialNo;
	private String Specification;
	private String DateOfPeriodicSubs;
	private String TargetDistributorCode;
	private String TargetBranchCode;
	private String TargetTransactionAccountID;
	private String TargetRegionCode;
	private String TransferDirection;
	private String DefDividendMethod;
	private String DividendRatio;
	private String Interest;
	private String VolumeByInterest;
	private String InterestTax;
	private String TradingPrice;
	private String FreezingDeadline;
	private String FrozenCause;
	private String Tax;
	private String TargetNAV;
	private String TargetFundPrice;
	private String CfmVolOfTargetFund;
	private String MinFee;
	private String OtherFee2;
	private String OriginalAppDate;
	private String TransferFee;
	private String FromTAFlag;
	private String ShareClass;
	private String DetailFlag;
	private String RedemptionInAdvanceFlag;
	private String FrozenMethod;
	private String OriginalCfmDate;
	private String RedemptionReason;
	private String CodeOfTargetFund;
	private String TotalTransFee;
	private String VarietyCodeOfPeriodicSubs;
	private String SerialNoOfPeriodicSubs;
	private String RationType;
	private String TargetTAAccountID;
	private String TargetRegistrarCode;
	private String NetNo;
	private String CustomerNo;
	private String TargetShareType;
	private String RationProtocolNo;
	private String BeginDateOfPeriodicSubs;
	private String EndDateOfPeriodicSubs;
	private String SendDayOfPeriodicSubs;
	private String Broker;
	private String SalesPromotion;
	private String AcceptMethod;
	private String ForceRedemptionType;
	private String AlternationDate;
	private String TakeIncomeFlag;
	private String PurposeOfPeSubs;
	private String FrequencyOfPeSubs;
	private String PeriodSubTimeUnit;
	private String BatchNumOfPeSubs;
	private String CapitalMode;
	private String DetailCapticalMode;
	private String BackenloadDiscount;
	private String CombineNum;
	private String RefundAmount;
	private String SalePercent;
	private String ManagerRealRatio;
	private String ChangeFee;
	private String RecuperateFee;
	private String AchievementPay;
	private String AchievementCompen;
	private String SharesAdjustmentFlag;
	private String GeneralTASerialNO;
	private String UndistributeMonetaryIncome;
	private String UndistributeMonetaryIncomeFlag;
	private String BreachFee;
	private String BreachFeeBackToFund;
	private String PunishFee;
	private String TradingMethod;
	private String ChangeAgencyFee;
	private String RecuperateAgencyFee;
	private String ErrorDetail;
	private String LargeBuyFlag;
	private String RaiseInterest;
	private String FeeCalculator;
	private String ShareRegisterDate;
	private String TotalFrozenVol;
	private String FundVolBalance;
	private String FrozenBalance;
	private String FutureSubscribeDate;
	private String TransferDateThroughClearingAgency;

	@Override
	public TableModel newInstanceWithoutArgs() { return new File04(); }
}