package com.example.pojo;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class FundParaConfig {
	private int FundParaID;
	private String DistributorCode;
	private String FundCode;
	private String DownLoaddate;
	private String PrdRiskRate;
	private String DebtFundType;
	private String AllowClientGroup;
	private String FinancialRegistrationCode;
	private String SaleObject;
	private String IsCycleFund;
	private String CycleDays;
	private String CycleNums;
	private String DefCycleNums;
	private Double BreachOfContractFee;
	private String LCFundType;
	private String IPOType;
	private String InvestmentTargets;
	private String ClearDays;
	private String RedeemAmtDays;
	private String DivAmtDays;
	private String FundEndDays;
	private String FundIssuanceFailDays;
	private String CashFlag;
	private String IncomeEndDate;
	private String IncomeCurrType;
	private String CostCurrType;
	private String ChoiceBonusType;
	private String CancelOrderType;
	private Double BuyUpperLimitday;
	private String IsPartRedeem;
	private Double LargeRedeemRatio;
	private String RedeemAmtReturn;
	private String FundMinBala;
	private Double FundMaXBala;
	private String Subscribemode;
	private String Purchasemode;
	private Double RealRedeemRatio;
	private Double RealRedeemUpperLimitOfDay;
	private Double RealRedeemUpperLimitOfSolo;
	private String ShareDoMethod;
	private Double OrgRedeemBase;
	private Double PerRedeemBase;
	private Double ComparisonRatio;
	private String FundIssuer;
	private String ManagementBasic;
	private Double ExcessiveRtio;
	private String SubBasic;
	private String SubDelayedDays;
	private String FundCollectAccount;
	private String ExcessiveSubRtio;
	private Double InterestRate;
	private String OpenTime;
	private String CloseTime;
	private String ShareClass;
	private String FundNameAbbr;
	private String FinancType;
	private String IsGuaranteedFund;
	private String IsLOFFund;
	private String IsQDIIFund;
	private String IsETFFund;
	private Double LxRedeemFeeBackRatio;
	private String RedemptionSequence;
	private Double BuyUpperAmount;
	private Double CovertInUpperAmount;
	private Double PeriodSubUpperAmount;
	private String FundEstablishDate;
	private String ExchangeFlag;
	private String Specification;
	private String WholeFlag;
	private String ModifyWay;
	private String OperateDate;
	private Double IssPrice;
	private String IncomeDate;
	private Double OMinAccountBalance;
	private Double PMinRedemptionVol;
	private Double PMinInterconvertVol;
	private Double OMinRedemptionVol;
	private Double OMinInterconvertVol;
	private String SubcancelFlag;
	private String InterestWay;
	private String PrdProfitKind;
	private String IsAllowPrdRealTimeRansom;
	private String BaseDays;
	private String TransWay;
	private String ParentsPrdCode;
	private String PrdTemplateCode;
	private String AlimitEndDate;
	private Double ORedUnit;
	private Double OMaxAccuAmt;
	private Double PRedUnit;
	private Double PMaxAccuAmt;
	private String ModelCOMMENT;
	private String DayBeforeCfm;
	private String BuyIsControlConfirmFlag;
	private String RedeemIsControlConfirmFlag;
	private String ZeroSetUpFlag;
	private String LimitFlag;
	private String AgioType;
	private Double SellerLimit;
	private Double LockDays;
	private String IsCheckInvester;
	private String ClientCycleMode;
	private Double MinCycleDays;
	private Double MaxCyleDays;
	private String CycleAllottedDays;
	private String FundBuyAccount;
	private String TACode;
}